extends:
  - standard
  - standard-react
  - prettier

parser: babel-eslint

plugins:
  - prettier

rules:
  prettier/prettier:
    - error
    - trailingComma: es5
      singleQuote: true
      semi: true

  react/prop-types: false
